seed: 13
split_pct: 0.7
window_length: 10
hidden_layers: 1
hidden_units: 8
batch_size: 256
n_epochs: 150
activation_dense: relu
learning_rate: 0.0008
dropout: 0.2
stop_patience: 15
lr_schedule_patience: 5
